# Generated by Django 4.1.4 on 2022-12-28 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sell', '0002_sellitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Berilgan Pul')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Mijoz')),
                ('sellitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.sellitem', verbose_name='Sell Item')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Qaytarilgan Mahsulot',
                'verbose_name_plural': 'Qaytarilgan Mahsulotlar',
            },
        ),
    ]
