# Generated by Django 4.1.4 on 2022-12-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0002_alter_partner_qarz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Mahsulot kodi')),
                ('title', models.CharField(max_length=50, verbose_name='Mahsulot nomi')),
                ('hajmi', models.IntegerField(verbose_name='Bitta mahsulot hajmi')),
                ('nechta', models.IntegerField(verbose_name='Mahsulot nechta')),
                ('narx', models.IntegerField(verbose_name='Narxi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('nechta', models.IntegerField(null=True, verbose_name='Mahsulot nechta')),
                ('bir_hajmi', models.CharField(max_length=50, verbose_name='Bitta mahsulot hajmi')),
                ('bir_narx', models.IntegerField(verbose_name='Bitta mahsulot narxi')),
                ('sotiladigan', models.IntegerField(verbose_name='Sotiladigan narxi')),
                ('um_narx', models.IntegerField(verbose_name='Umumiy narx')),
                ('tolandi', models.BooleanField(null=True, verbose_name="Umumiy pul to'landimi")),
                ('qancha', models.IntegerField(null=True, verbose_name="Qancha pul to'landi")),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Hamkor')),
            ],
            options={
                'verbose_name': 'Yangi mahsulot',
                'verbose_name_plural': 'Yangi mahsulotlar',
            },
        ),
    ]
