# Generated by Django 4.1.5 on 2023-01-09 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0003_alter_partner_p_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.IntegerField(max_length=10000, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Mahsulot nomi')),
                ('kelgan_narx', models.IntegerField(verbose_name='Kelgan narxi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('nechta', models.IntegerField(null=True, verbose_name='Mahsulot nechta')),
                ('bir_hajmi', models.CharField(max_length=50, verbose_name='Bitta mahsulot hajmi')),
                ('um_narx', models.IntegerField(verbose_name='Umumiy narx')),
                ('hamkor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Hamkor')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Yangi mahsulot',
                'verbose_name_plural': 'Yangi mahsulotlar',
            },
        ),
    ]
