# Generated by Django 4.1.7 on 2023-03-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=10000, null=True)),
                ('name', models.CharField(max_length=50)),
                ('incoming_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(null=True)),
                ('size', models.CharField(max_length=50)),
                ('total_price', models.IntegerField()),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.dealer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
