# Generated by Django 4.1.5 on 2023-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ulchovi',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
