# Generated by Django 4.1.7 on 2023-03-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.measure'),
        ),
    ]
