# Generated by Django 4.1.4 on 2022-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hajmi',
            field=models.CharField(max_length=20, verbose_name='Bitta mahsulot hajmi'),
        ),
    ]
