# Generated by Django 4.1.5 on 2023-01-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_ulchovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ulchovi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
