# Generated by Django 4.1.5 on 2023-01-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_ulchovi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nechta',
            field=models.IntegerField(null=True),
        ),
    ]
