# Generated by Django 4.1.7 on 2023-03-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('p_num', models.CharField(max_length=20, verbose_name='Phone number')),
                ('debt', models.IntegerField(blank=True, default=0, null=True, verbose_name='Debt')),
            ],
        ),
    ]
