# Generated by Django 4.1.5 on 2023-01-09 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarajatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqti', models.DateField(auto_now=True, verbose_name='Vaqt')),
                ('total_price', models.IntegerField(blank=True, default=0, null=True)),
                ('chegirma', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Mijoz')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Sotildi',
                'verbose_name_plural': 'Sotilganlar',
            },
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Mahsulot')),
                ('sell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.sell')),
            ],
            options={
                'verbose_name': 'SellItem',
                'verbose_name_plural': 'SellItems',
            },
        ),
        migrations.CreateModel(
            name='Harajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pul', models.IntegerField(verbose_name='Ishlatilgan pul')),
                ('ishchi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ishchi')),
                ('sabab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.harajatcategory')),
            ],
            options={
                'verbose_name': 'Harajat',
                'verbose_name_plural': 'Harajatlar',
            },
        ),
    ]
