# Generated by Django 4.1.5 on 2023-01-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='vaqti',
            field=models.DateTimeField(auto_now=True, verbose_name='Vaqt'),
        ),
    ]
