# Generated by Django 4.1.7 on 2023-02-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='worker_iz',
            new_name='worker',
        ),
    ]
