# Generated by Django 4.1.4 on 2022-12-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Sotilgan narx'),
        ),
    ]
