# Generated by Django 4.1.5 on 2023-01-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_alter_sell_vaqti'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='chegirma',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
