# Generated by Django 4.1.7 on 2023-02-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sell', '0002_rename_worker_iz_cost_worker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sell',
            options={},
        ),
        migrations.AlterField(
            model_name='sell',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
