# Generated by Django 4.1.5 on 2023-01-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_sellitem_chegirma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='chegirma',
        ),
    ]
