# Generated by Django 4.1.4 on 2022-12-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_alter_sell_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='date',
        ),
    ]
