# Generated by Django 4.1.7 on 2023-03-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_rename_product_id_sellitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
