# Generated by Django 4.1.4 on 2022-12-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_remove_sell_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Vaqt'),
        ),
    ]
