# Generated by Django 4.1.5 on 2023-01-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_remove_sell_chegirma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
