# Generated by Django 4.1.5 on 2023-01-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_alter_sellitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='chegirma',
            field=models.IntegerField(default=0, null=True, verbose_name='Bitta mahsulot uchun chegirma'),
        ),
    ]
