# Generated by Django 4.1.5 on 2023-01-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_alter_sellitem_chegirma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='vaqti',
            field=models.DateTimeField(verbose_name='Vaqt'),
        ),
    ]
