# Generated by Django 4.1.5 on 2023-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_alter_sell_vaqti'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
