# Generated by Django 4.1.5 on 2023-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='qarz',
        ),
        migrations.AddField(
            model_name='partner',
            name='p_num',
            field=models.IntegerField(null=True),
        ),
    ]
