# Generated by Django 4.1.4 on 2022-12-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='qarz',
            field=models.IntegerField(blank=True, default=True, null=True, verbose_name="Do'kon qarzi"),
        ),
    ]
