# Generated by Django 4.1.5 on 2023-01-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_remove_partner_qarz_partner_p_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='p_num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
